---
title: "Instacart"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(viridis)
library(p8105.datasets)
library(plotly)
data("instacart")
```

```{r tidy_data}
set.seed(1)
inst = 
  instacart %>% 
janitor::clean_names() %>% 
sample_n(5000)
```

Column {data-width=650}
-----------------------------------------------------------------------

### order counts of different departments

```{r warning = FALSE}
  inst %>% 
  count(department) %>% 
  mutate(department = fct_reorder(department,n)) %>%
  plot_ly(x = ~department, y = ~n, color = ~department, type = "bar")
```

Column {data-width=550}
-----------------------------------------------------------------------

### days since prior order of different departments

```{r warning = FALSE}
box = 
inst %>% 
  ggplot(aes(x = department,y = days_since_prior_order, color = department))+
  geom_boxplot() +
  theme(axis.text.x = element_text(angle = 90, size = 3.5))
ggplotly(box)

```

### ?

```{r}
  inst %>% 
  group_by(order_dow,order_hour_of_day) %>% 
  summarise(
    count = n()
  ) %>% 
  plot_ly(x = ~order_hour_of_day, y = ~count,  type = "box")

```